import {
  Coins, BarChart3, Building2, Globe, Brain, Gamepad2, Zap, Wrench,
  ImageIcon, Clapperboard, Briefcase, Map, Sparkles, MessageCircle,
  GraduationCap, Palette, TrendingUp, Target, Flame, Trophy, BookOpen,
  Star, Lock, Bot, Rocket, Search, Newspaper, ScrollText, Pencil,
  Shuffle, Lightbulb, Calendar, Home, Smartphone, Monitor, FileText,
  CheckCircle2, AlertTriangle, Shield, Mic, Scale, Sprout, ShoppingCart,
  type LucideIcon
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  coins: Coins,
  'bar-chart-3': BarChart3,
  'building-2': Building2,
  globe: Globe,
  brain: Brain,
  'gamepad-2': Gamepad2,
  zap: Zap,
  wrench: Wrench,
  image: ImageIcon,
  clapperboard: Clapperboard,
  briefcase: Briefcase,
  map: Map,
  sparkles: Sparkles,
  'message-circle': MessageCircle,
  'graduation-cap': GraduationCap,
  palette: Palette,
  'trending-up': TrendingUp,
  target: Target,
  flame: Flame,
  trophy: Trophy,
  'book-open': BookOpen,
  star: Star,
  lock: Lock,
  bot: Bot,
  rocket: Rocket,
  search: Search,
  newspaper: Newspaper,
  'scroll-text': ScrollText,
  pencil: Pencil,
  shuffle: Shuffle,
  lightbulb: Lightbulb,
  calendar: Calendar,
  home: Home,
  smartphone: Smartphone,
  monitor: Monitor,
  'file-text': FileText,
  'check-circle-2': CheckCircle2,
  'alert-triangle': AlertTriangle,
  shield: Shield,
  mic: Mic,
  scale: Scale,
  sprout: Sprout,
  'shopping-cart': ShoppingCart,
};

export type IconName = keyof typeof iconMap;
