export interface RoleData {
  title: string;
  category: string;
  baseImpactScore: number;
  automatableTasks: string[];
  humanTasks: string[];
  aiAdvantages: string[];
  impactTimelineYears: [number, number];
}

export interface CountryData {
  name: string;
  adoptionMultiplier: number;
  regulatoryContext: string;
}

export const COUNTRIES: CountryData[] = [
  { name: "Australia", adoptionMultiplier: 1.1, regulatoryContext: "Australia is developing a risk-based AI governance framework with strong emphasis on responsible AI principles and voluntary codes of practice." },
  { name: "Bangladesh", adoptionMultiplier: 0.7, regulatoryContext: "Bangladesh is in early stages of AI adoption, with the government focusing on digital infrastructure and skills development." },
  { name: "Brunei", adoptionMultiplier: 0.75, regulatoryContext: "Brunei's Vision 2035 includes digital transformation goals, with AI adoption gradually increasing in government services." },
  { name: "Cambodia", adoptionMultiplier: 0.7, regulatoryContext: "Cambodia's digital economy is growing rapidly, with AI adoption concentrated in fintech and agriculture sectors." },
  { name: "China", adoptionMultiplier: 1.3, regulatoryContext: "China leads in AI deployment with comprehensive regulations including algorithmic recommendation rules and generative AI governance. Aggressive adoption across all industries." },
  { name: "Hong Kong", adoptionMultiplier: 1.15, regulatoryContext: "Hong Kong follows a pro-innovation approach with sector-specific AI guidelines, particularly strong in financial services AI adoption." },
  { name: "India", adoptionMultiplier: 1.05, regulatoryContext: "India is rapidly scaling AI across government and enterprise, with a focus on AI for development and a growing regulatory framework." },
  { name: "Indonesia", adoptionMultiplier: 0.85, regulatoryContext: "Indonesia's national AI strategy emphasizes ethical AI and digital talent development, with growing adoption in banking and e-commerce." },
  { name: "Japan", adoptionMultiplier: 1.15, regulatoryContext: "Japan favours innovation-friendly, sector-specific AI governance with strong industry self-regulation. Labour shortages accelerate AI adoption." },
  { name: "Laos", adoptionMultiplier: 0.65, regulatoryContext: "Laos is at an early stage of AI adoption, with development focused on agricultural technology and basic digital services." },
  { name: "Malaysia", adoptionMultiplier: 0.95, regulatoryContext: "Malaysia's national AI roadmap targets key industries, with growing AI adoption in manufacturing, finance, and public services." },
  { name: "Mongolia", adoptionMultiplier: 0.7, regulatoryContext: "Mongolia is exploring AI in mining, agriculture, and governance, with digital infrastructure still developing." },
  { name: "Myanmar", adoptionMultiplier: 0.65, regulatoryContext: "AI adoption in Myanmar is limited, with digital development focused on telecommunications and basic connectivity." },
  { name: "Nepal", adoptionMultiplier: 0.65, regulatoryContext: "Nepal is beginning to explore AI in agriculture, health, and education, with international partnerships driving initial adoption." },
  { name: "New Zealand", adoptionMultiplier: 1.05, regulatoryContext: "New Zealand takes a principles-based approach to AI governance, with a focus on transparency, fairness, and Treaty of Waitangi considerations." },
  { name: "Pakistan", adoptionMultiplier: 0.75, regulatoryContext: "Pakistan's AI policy focuses on economic growth and skills development, with adoption growing in IT outsourcing and fintech." },
  { name: "Philippines", adoptionMultiplier: 0.85, regulatoryContext: "The Philippines is investing in AI for BPO transformation and government services, with a focus on upskilling the services workforce." },
  { name: "Singapore", adoptionMultiplier: 1.25, regulatoryContext: "Singapore leads in AI governance with its Model AI Governance Framework and strong public-private partnerships. Very high enterprise adoption." },
  { name: "South Korea", adoptionMultiplier: 1.2, regulatoryContext: "South Korea combines aggressive AI investment with emerging regulation, strong in manufacturing AI and digital government services." },
  { name: "Sri Lanka", adoptionMultiplier: 0.75, regulatoryContext: "Sri Lanka is developing its AI strategy with a focus on IT services, tourism tech, and agricultural applications." },
  { name: "Taiwan", adoptionMultiplier: 1.1, regulatoryContext: "Taiwan's AI strategy leverages its semiconductor ecosystem, with strong adoption in manufacturing, healthcare, and smart city applications." },
  { name: "Thailand", adoptionMultiplier: 0.9, regulatoryContext: "Thailand's national AI strategy targets manufacturing, agriculture, and healthcare, with growing adoption in banking and retail." },
  { name: "Vietnam", adoptionMultiplier: 0.9, regulatoryContext: "Vietnam's AI strategy emphasises economic competitiveness, with rapid adoption in manufacturing, fintech, and software development." },
];

export const ROLES: RoleData[] = [
  // Technology
  { title: "Software Developer", category: "Technology", baseImpactScore: 45, automatableTasks: ["Boilerplate code generation", "Unit test writing", "Code documentation", "Bug detection and simple fixes"], humanTasks: ["System architecture design", "Understanding business requirements", "Creative problem solving", "Code review and mentoring"], aiAdvantages: ["Use AI coding assistants to 10x productivity", "Automate repetitive development tasks", "Focus on higher-level design and strategy"], impactTimelineYears: [2, 5] },
  { title: "Data Scientist", category: "Technology", baseImpactScore: 35, automatableTasks: ["Data cleaning and preprocessing", "Feature engineering suggestions", "Standard model selection", "Report generation"], humanTasks: ["Problem framing and hypothesis generation", "Interpreting results in business context", "Ethical considerations", "Novel research directions"], aiAdvantages: ["AutoML for rapid prototyping", "AI-assisted feature discovery", "Automated experiment tracking"], impactTimelineYears: [3, 7] },
  { title: "Data Analyst", category: "Technology", baseImpactScore: 55, automatableTasks: ["Standard report generation", "Data visualisation from templates", "SQL query writing", "Trend identification"], humanTasks: ["Strategic insight generation", "Stakeholder communication", "Defining metrics and KPIs", "Cross-functional collaboration"], aiAdvantages: ["Natural language data querying", "Automated dashboard creation", "AI-powered anomaly detection"], impactTimelineYears: [1, 4] },
  { title: "DevOps Engineer", category: "Technology", baseImpactScore: 40, automatableTasks: ["Infrastructure provisioning", "Log analysis and alerting", "Configuration management", "Routine deployment tasks"], humanTasks: ["Architecture decisions", "Incident response leadership", "Security strategy", "Cross-team coordination"], aiAdvantages: ["AIOps for predictive maintenance", "Automated incident triage", "Infrastructure optimization"], impactTimelineYears: [2, 5] },
  { title: "QA Engineer", category: "Technology", baseImpactScore: 60, automatableTasks: ["Test case generation", "Regression testing", "Bug report writing", "Performance test scripting"], humanTasks: ["Test strategy design", "Exploratory testing", "Usability assessment", "Risk-based prioritisation"], aiAdvantages: ["AI-powered test generation", "Visual regression detection", "Intelligent test prioritisation"], impactTimelineYears: [1, 4] },
  { title: "IT Support Specialist", category: "Technology", baseImpactScore: 65, automatableTasks: ["Password resets and account management", "Tier-1 troubleshooting", "Knowledge base responses", "System monitoring alerts"], humanTasks: ["Complex issue diagnosis", "User training and education", "Infrastructure planning", "Vendor relationship management"], aiAdvantages: ["AI chatbots for first-line support", "Predictive issue detection", "Automated ticket routing"], impactTimelineYears: [1, 3] },
  { title: "Cybersecurity Analyst", category: "Technology", baseImpactScore: 30, automatableTasks: ["Threat detection pattern matching", "Log analysis and correlation", "Vulnerability scanning", "Compliance report generation"], humanTasks: ["Threat hunting and investigation", "Security architecture design", "Incident response strategy", "Risk assessment and communication"], aiAdvantages: ["AI-powered threat detection", "Automated security posture assessment", "Behavioural anomaly detection"], impactTimelineYears: [3, 7] },
  { title: "Product Manager", category: "Technology", baseImpactScore: 30, automatableTasks: ["Competitive analysis compilation", "User feedback categorisation", "Sprint report generation", "Market research aggregation"], humanTasks: ["Product vision and strategy", "Stakeholder alignment", "Prioritisation decisions", "User empathy and research"], aiAdvantages: ["AI-driven user behaviour analysis", "Automated A/B test analysis", "Market trend prediction"], impactTimelineYears: [3, 8] },
  { title: "UX Designer", category: "Technology", baseImpactScore: 40, automatableTasks: ["Wireframe generation from specs", "Design system component creation", "Accessibility audit checking", "Prototype iteration"], humanTasks: ["User research and empathy mapping", "Design thinking facilitation", "Brand experience strategy", "Complex interaction design"], aiAdvantages: ["AI-generated design variations", "Automated usability analysis", "Rapid prototyping with AI tools"], impactTimelineYears: [2, 6] },
  { title: "Cloud Architect", category: "Technology", baseImpactScore: 25, automatableTasks: ["Cost optimisation recommendations", "Infrastructure sizing", "Migration planning templates", "Compliance checking"], humanTasks: ["Multi-cloud strategy design", "Security architecture", "Business continuity planning", "Vendor evaluation"], aiAdvantages: ["AI-driven cost optimization", "Predictive scaling", "Automated architecture recommendations"], impactTimelineYears: [4, 8] },
  { title: "Systems Administrator", category: "Technology", baseImpactScore: 55, automatableTasks: ["Server provisioning", "Patch management", "Backup scheduling", "Performance monitoring"], humanTasks: ["Capacity planning", "Disaster recovery strategy", "Security hardening", "Migration planning"], aiAdvantages: ["Predictive system maintenance", "Automated remediation", "Intelligent resource allocation"], impactTimelineYears: [2, 5] },
  { title: "Database Administrator", category: "Technology", baseImpactScore: 50, automatableTasks: ["Query optimisation", "Index recommendations", "Backup management", "Performance tuning"], humanTasks: ["Data architecture design", "Migration strategy", "Security policy design", "Capacity planning"], aiAdvantages: ["AI-powered query optimization", "Automated performance tuning", "Predictive storage management"], impactTimelineYears: [2, 5] },
  { title: "Mobile App Developer", category: "Technology", baseImpactScore: 45, automatableTasks: ["UI component generation", "API integration boilerplate", "Test automation", "App store listing optimization"], humanTasks: ["User experience innovation", "Platform-specific optimisation", "Architecture decisions", "Performance tuning"], aiAdvantages: ["AI code generation tools", "Automated UI testing", "Design-to-code conversion"], impactTimelineYears: [2, 5] },
  { title: "Machine Learning Engineer", category: "Technology", baseImpactScore: 30, automatableTasks: ["Hyperparameter tuning", "Model benchmarking", "Data pipeline setup", "Standard model deployment"], humanTasks: ["Novel architecture research", "Domain-specific model design", "Ethics and bias evaluation", "Production system reliability"], aiAdvantages: ["AutoML for rapid experimentation", "AI-assisted code review", "Automated model monitoring"], impactTimelineYears: [4, 8] },
  { title: "Network Engineer", category: "Technology", baseImpactScore: 45, automatableTasks: ["Network monitoring", "Configuration management", "Troubleshooting common issues", "Documentation"], humanTasks: ["Network architecture design", "Security strategy", "Vendor negotiations", "Capacity planning"], aiAdvantages: ["AI-driven network optimization", "Predictive fault detection", "Automated configuration management"], impactTimelineYears: [2, 6] },
  { title: "Technical Writer", category: "Technology", baseImpactScore: 65, automatableTasks: ["API documentation generation", "Release notes drafting", "Code comment extraction", "Template-based guides"], humanTasks: ["Complex concept explanation", "Information architecture", "User journey mapping", "Style and brand consistency"], aiAdvantages: ["AI-assisted first drafts", "Automated documentation updates", "Multi-language translation"], impactTimelineYears: [1, 3] },
  { title: "Web Developer", category: "Technology", baseImpactScore: 50, automatableTasks: ["Landing page generation", "CSS styling from designs", "Basic API integration", "Cross-browser testing"], humanTasks: ["Complex interaction design", "Performance optimization", "Accessibility expertise", "Client communication"], aiAdvantages: ["AI website builders", "Code generation from designs", "Automated testing tools"], impactTimelineYears: [1, 4] },
  { title: "Blockchain Developer", category: "Technology", baseImpactScore: 35, automatableTasks: ["Smart contract auditing", "Standard token deployment", "Test writing", "Documentation"], humanTasks: ["Protocol design", "Security architecture", "Tokenomics design", "Community governance"], aiAdvantages: ["AI-powered code auditing", "Automated vulnerability detection", "Smart contract optimization"], impactTimelineYears: [3, 7] },
  // Finance
  { title: "Accountant", category: "Finance", baseImpactScore: 72, automatableTasks: ["Bookkeeping and data entry", "Invoice processing", "Bank reconciliation", "Standard tax return preparation"], humanTasks: ["Tax strategy and planning", "Client advisory services", "Complex audit judgements", "Regulatory interpretation"], aiAdvantages: ["AI-powered bookkeeping automation", "Intelligent expense categorisation", "Real-time financial insights"], impactTimelineYears: [1, 4] },
  { title: "Financial Analyst", category: "Finance", baseImpactScore: 55, automatableTasks: ["Financial model building", "Data gathering and compilation", "Standard report generation", "Variance analysis"], humanTasks: ["Strategic recommendations", "Investor communication", "Risk judgement", "Market narrative interpretation"], aiAdvantages: ["AI-powered financial modelling", "Automated market screening", "Predictive analytics"], impactTimelineYears: [2, 5] },
  { title: "Bank Teller", category: "Finance", baseImpactScore: 85, automatableTasks: ["Cash transactions", "Account inquiries", "Balance checks", "Simple transfers"], humanTasks: ["Complex problem resolution", "Relationship building", "Fraud detection escalation", "Financial product advisory"], aiAdvantages: ["Transition to advisory roles", "AI-assisted customer insights", "Digital banking expertise"], impactTimelineYears: [1, 3] },
  { title: "Insurance Underwriter", category: "Finance", baseImpactScore: 68, automatableTasks: ["Standard risk assessment", "Policy pricing calculations", "Document verification", "Claims data analysis"], humanTasks: ["Complex risk evaluation", "Policy exceptions", "Relationship management", "Emerging risk assessment"], aiAdvantages: ["AI risk scoring models", "Automated document processing", "Predictive claims analysis"], impactTimelineYears: [2, 5] },
  { title: "Loan Officer", category: "Finance", baseImpactScore: 70, automatableTasks: ["Credit scoring", "Document verification", "Standard loan processing", "Compliance checking"], humanTasks: ["Complex case assessment", "Client relationship management", "Exception handling", "Community lending knowledge"], aiAdvantages: ["AI credit assessment tools", "Automated application processing", "Risk prediction models"], impactTimelineYears: [1, 4] },
  { title: "Investment Banker", category: "Finance", baseImpactScore: 40, automatableTasks: ["Financial modelling", "Market research compilation", "Pitch deck data population", "Due diligence document review"], humanTasks: ["Deal origination and relationships", "Negotiation strategy", "Strategic advisory", "Client management"], aiAdvantages: ["AI-powered deal screening", "Automated financial analysis", "Market intelligence tools"], impactTimelineYears: [3, 7] },
  { title: "Compliance Officer", category: "Finance", baseImpactScore: 50, automatableTasks: ["Transaction monitoring", "Regulatory report generation", "Policy document review", "KYC data verification"], humanTasks: ["Regulatory interpretation", "Policy design", "Risk assessment judgement", "Stakeholder advisory"], aiAdvantages: ["AI-powered transaction screening", "Regulatory change monitoring", "Automated compliance reporting"], impactTimelineYears: [2, 5] },
  { title: "Tax Advisor", category: "Finance", baseImpactScore: 45, automatableTasks: ["Standard tax calculations", "Filing preparation", "Deduction identification", "Compliance checking"], humanTasks: ["Tax planning strategy", "Cross-border structuring", "Client advisory", "Regulatory interpretation"], aiAdvantages: ["AI tax optimisation tools", "Automated filing systems", "Regulation change tracking"], impactTimelineYears: [2, 6] },
  { title: "Actuary", category: "Finance", baseImpactScore: 40, automatableTasks: ["Standard statistical modelling", "Data processing and analysis", "Routine pricing calculations", "Report generation"], humanTasks: ["Model design and innovation", "Risk interpretation", "Strategic advisory", "Regulatory compliance strategy"], aiAdvantages: ["AI-enhanced predictive models", "Automated scenario analysis", "Real-time risk monitoring"], impactTimelineYears: [3, 7] },
  { title: "Trader", category: "Finance", baseImpactScore: 60, automatableTasks: ["Order execution", "Market data analysis", "Portfolio rebalancing", "Risk metrics calculation"], humanTasks: ["Strategy development", "Market sentiment interpretation", "Client relationships", "Crisis decision-making"], aiAdvantages: ["Algorithmic trading strategies", "AI market analysis", "Automated risk management"], impactTimelineYears: [1, 4] },
  // Healthcare
  { title: "Doctor", category: "Healthcare", baseImpactScore: 20, automatableTasks: ["Medical image analysis assistance", "Drug interaction checking", "Appointment scheduling", "Patient record summarisation"], humanTasks: ["Patient diagnosis and judgement", "Empathetic communication", "Treatment planning", "Ethical decision-making"], aiAdvantages: ["AI diagnostic support tools", "Medical research acceleration", "Personalised treatment recommendations"], impactTimelineYears: [5, 10] },
  { title: "Nurse", category: "Healthcare", baseImpactScore: 15, automatableTasks: ["Vital signs monitoring", "Medication reminders", "Documentation and charting", "Scheduling management"], humanTasks: ["Patient care and compassion", "Clinical assessment", "Crisis response", "Patient advocacy"], aiAdvantages: ["AI-assisted patient monitoring", "Predictive health alerts", "Streamlined documentation"], impactTimelineYears: [5, 10] },
  { title: "Pharmacist", category: "Healthcare", baseImpactScore: 55, automatableTasks: ["Prescription dispensing", "Drug interaction checking", "Inventory management", "Insurance processing"], humanTasks: ["Patient counselling", "Complex medication reviews", "Immunisation services", "Healthcare team collaboration"], aiAdvantages: ["AI drug interaction analysis", "Automated dispensing systems", "Personalised medication advice"], impactTimelineYears: [3, 7] },
  { title: "Radiologist", category: "Healthcare", baseImpactScore: 50, automatableTasks: ["Standard image screening", "Measurement calculations", "Report template generation", "Case prioritisation"], humanTasks: ["Complex case interpretation", "Interventional procedures", "Clinical correlation", "Patient communication"], aiAdvantages: ["AI-powered image analysis", "Automated detection tools", "Workflow optimisation"], impactTimelineYears: [3, 7] },
  { title: "Medical Lab Technician", category: "Healthcare", baseImpactScore: 60, automatableTasks: ["Sample processing", "Standard test execution", "Result recording", "Quality control checks"], humanTasks: ["Complex test troubleshooting", "Equipment maintenance", "Result interpretation", "Method development"], aiAdvantages: ["Automated sample analysis", "AI quality assurance", "Predictive equipment maintenance"], impactTimelineYears: [2, 6] },
  { title: "Physical Therapist", category: "Healthcare", baseImpactScore: 15, automatableTasks: ["Exercise plan generation", "Progress tracking", "Appointment scheduling", "Documentation"], humanTasks: ["Hands-on treatment", "Patient motivation", "Assessment and diagnosis", "Adaptive treatment modification"], aiAdvantages: ["AI-powered motion analysis", "Personalised exercise programs", "Remote monitoring tools"], impactTimelineYears: [5, 10] },
  { title: "Dentist", category: "Healthcare", baseImpactScore: 18, automatableTasks: ["X-ray analysis assistance", "Appointment scheduling", "Treatment plan costing", "Record keeping"], humanTasks: ["Clinical procedures", "Patient communication", "Treatment decisions", "Emergency care"], aiAdvantages: ["AI diagnostic imaging", "Treatment planning assistance", "Practice management automation"], impactTimelineYears: [5, 10] },
  { title: "Mental Health Counsellor", category: "Healthcare", baseImpactScore: 12, automatableTasks: ["Session scheduling", "Progress note templates", "Resource recommendations", "Assessment scoring"], humanTasks: ["Therapeutic relationship", "Active listening", "Clinical judgement", "Crisis intervention"], aiAdvantages: ["AI-assisted mood tracking", "Research-backed intervention suggestions", "Administrative automation"], impactTimelineYears: [7, 12] },
  // Education
  { title: "Teacher", category: "Education", baseImpactScore: 25, automatableTasks: ["Grading standardised tests", "Lesson plan templates", "Progress report generation", "Administrative paperwork"], humanTasks: ["Student mentoring and inspiration", "Classroom management", "Social-emotional development", "Adaptive teaching"], aiAdvantages: ["AI-personalised learning paths", "Automated grading assistance", "Content creation tools"], impactTimelineYears: [3, 8] },
  { title: "University Lecturer", category: "Education", baseImpactScore: 30, automatableTasks: ["Lecture slide preparation", "Assignment grading", "Research literature review", "Administrative tasks"], humanTasks: ["Research innovation", "Student mentorship", "Critical thinking facilitation", "Academic leadership"], aiAdvantages: ["AI research assistants", "Automated assessment tools", "Personalised student feedback"], impactTimelineYears: [3, 8] },
  { title: "Tutor", category: "Education", baseImpactScore: 55, automatableTasks: ["Basic concept explanation", "Practice problem generation", "Progress tracking", "Study material compilation"], humanTasks: ["Emotional support and motivation", "Adaptive teaching strategies", "Complex concept breakdown", "Learning disability accommodation"], aiAdvantages: ["AI tutoring platforms", "Personalised practice exercises", "Performance analytics"], impactTimelineYears: [2, 5] },
  { title: "Librarian", category: "Education", baseImpactScore: 55, automatableTasks: ["Catalogue management", "Book recommendations", "Basic reference queries", "Digital resource indexing"], humanTasks: ["Community programming", "Research guidance", "Information literacy teaching", "Collection development strategy"], aiAdvantages: ["AI-powered search and discovery", "Automated cataloguing", "Personalised reading recommendations"], impactTimelineYears: [2, 5] },
  { title: "School Administrator", category: "Education", baseImpactScore: 40, automatableTasks: ["Scheduling", "Report generation", "Budget tracking", "Communication templates"], humanTasks: ["Leadership and vision", "Community engagement", "Staff development", "Crisis management"], aiAdvantages: ["AI scheduling optimisation", "Predictive enrollment analytics", "Automated communications"], impactTimelineYears: [3, 7] },
  { title: "Corporate Trainer", category: "Education", baseImpactScore: 50, automatableTasks: ["Training material creation", "Assessment generation", "Progress tracking", "Scheduling and logistics"], humanTasks: ["Facilitation and engagement", "Needs assessment", "Custom program design", "Coaching and feedback"], aiAdvantages: ["AI-generated training content", "Adaptive learning platforms", "VR/AR training simulations"], impactTimelineYears: [2, 5] },
  // Legal
  { title: "Lawyer", category: "Legal", baseImpactScore: 35, automatableTasks: ["Legal research and case law search", "Document review and categorisation", "Contract clause analysis", "Due diligence document review"], humanTasks: ["Courtroom advocacy", "Client counselling", "Negotiation strategy", "Legal judgment and ethics"], aiAdvantages: ["AI legal research tools", "Contract analysis automation", "Predictive case outcome analysis"], impactTimelineYears: [3, 7] },
  { title: "Paralegal", category: "Legal", baseImpactScore: 65, automatableTasks: ["Document preparation", "Legal research compilation", "Filing and organisation", "Case timeline creation"], humanTasks: ["Client interaction support", "Complex document analysis", "Court procedure knowledge", "Case strategy support"], aiAdvantages: ["AI document automation", "Legal research acceleration", "Automated filing systems"], impactTimelineYears: [2, 5] },
  { title: "Legal Secretary", category: "Legal", baseImpactScore: 72, automatableTasks: ["Document formatting", "Calendar management", "Correspondence drafting", "Filing and records management"], humanTasks: ["Client relationship management", "Court filing procedures", "Confidentiality management", "Workflow coordination"], aiAdvantages: ["AI document generation", "Automated scheduling", "Intelligent filing systems"], impactTimelineYears: [1, 4] },
  { title: "Contract Manager", category: "Legal", baseImpactScore: 55, automatableTasks: ["Contract data extraction", "Renewal tracking", "Standard clause review", "Compliance checking"], humanTasks: ["Negotiation strategy", "Risk assessment", "Vendor relationships", "Complex dispute resolution"], aiAdvantages: ["AI contract analysis", "Automated risk flagging", "Lifecycle management tools"], impactTimelineYears: [2, 5] },
  { title: "Judge", category: "Legal", baseImpactScore: 10, automatableTasks: ["Case law research", "Scheduling", "Document management", "Statistical sentencing data"], humanTasks: ["Legal judgement and reasoning", "Courtroom management", "Ethical decision-making", "Precedent interpretation"], aiAdvantages: ["AI research assistants", "Case management tools", "Sentencing analytics"], impactTimelineYears: [7, 15] },
  // Creative
  { title: "Graphic Designer", category: "Creative", baseImpactScore: 55, automatableTasks: ["Template-based designs", "Image resizing and formatting", "Colour palette generation", "Social media post creation"], humanTasks: ["Brand strategy and identity", "Creative direction", "Client relationship management", "Complex visual storytelling"], aiAdvantages: ["AI design generation tools", "Rapid prototyping", "Automated asset variation"], impactTimelineYears: [1, 4] },
  { title: "Copywriter", category: "Creative", baseImpactScore: 65, automatableTasks: ["Product descriptions", "Email subject lines", "Social media posts", "SEO content generation"], humanTasks: ["Brand voice development", "Persuasion strategy", "Emotional storytelling", "Cultural nuance and localisation"], aiAdvantages: ["AI content generation", "A/B testing at scale", "Multilingual content creation"], impactTimelineYears: [1, 3] },
  { title: "Video Editor", category: "Creative", baseImpactScore: 45, automatableTasks: ["Rough cut assembly", "Colour correction", "Subtitle generation", "Clip selection from footage"], humanTasks: ["Narrative storytelling", "Emotional pacing", "Creative direction", "Client vision interpretation"], aiAdvantages: ["AI-assisted editing tools", "Automated colour grading", "Intelligent clip selection"], impactTimelineYears: [2, 5] },
  { title: "Photographer", category: "Creative", baseImpactScore: 35, automatableTasks: ["Basic photo editing", "Image sorting and tagging", "Batch processing", "Background removal"], humanTasks: ["Creative vision and composition", "Client direction", "Event management", "Lighting mastery"], aiAdvantages: ["AI editing and enhancement", "Automated cataloguing", "Style transfer tools"], impactTimelineYears: [3, 7] },
  { title: "Content Creator", category: "Creative", baseImpactScore: 50, automatableTasks: ["Content scheduling", "Hashtag research", "Performance analytics", "Thumbnail generation"], humanTasks: ["Authentic personality and voice", "Audience relationship building", "Trend interpretation", "Platform strategy"], aiAdvantages: ["AI content ideation", "Automated editing tools", "Analytics-driven strategy"], impactTimelineYears: [2, 5] },
  { title: "Illustrator", category: "Creative", baseImpactScore: 50, automatableTasks: ["Concept sketching", "Pattern generation", "Colour variations", "Asset scaling"], humanTasks: ["Unique artistic style", "Character design", "Client vision interpretation", "Storytelling through art"], aiAdvantages: ["AI concept generation", "Style exploration tools", "Rapid iteration assistance"], impactTimelineYears: [2, 5] },
  { title: "Animator", category: "Creative", baseImpactScore: 45, automatableTasks: ["In-between frame generation", "Lip sync animation", "Basic motion paths", "Asset rigging"], humanTasks: ["Character performance", "Storytelling", "Art direction", "Emotional expression"], aiAdvantages: ["AI-assisted animation tools", "Motion capture processing", "Automated lip sync"], impactTimelineYears: [2, 6] },
  { title: "Musician", category: "Creative", baseImpactScore: 30, automatableTasks: ["Background music generation", "Audio mastering", "Chord progression suggestions", "Loop creation"], humanTasks: ["Live performance", "Emotional expression", "Songwriting with meaning", "Audience connection"], aiAdvantages: ["AI composition tools", "Automated mixing", "Collaborative AI instruments"], impactTimelineYears: [3, 8] },
  { title: "Architect", category: "Creative", baseImpactScore: 35, automatableTasks: ["Floor plan generation", "3D rendering", "Building code checking", "Energy modelling"], humanTasks: ["Design vision and aesthetics", "Client consultation", "Site-specific solutions", "Sustainable design strategy"], aiAdvantages: ["AI-powered generative design", "Automated compliance checking", "Performance simulation"], impactTimelineYears: [3, 7] },
  // Manufacturing
  { title: "Factory Worker", category: "Manufacturing", baseImpactScore: 75, automatableTasks: ["Assembly line operations", "Quality inspection", "Packaging", "Material handling"], humanTasks: ["Complex maintenance", "Problem-solving anomalies", "Safety oversight", "Process improvement ideas"], aiAdvantages: ["Transition to robot supervision roles", "AI quality control systems", "Upskill to maintenance technician"], impactTimelineYears: [1, 5] },
  { title: "Quality Inspector", category: "Manufacturing", baseImpactScore: 70, automatableTasks: ["Visual defect detection", "Measurement verification", "Standard compliance checks", "Report generation"], humanTasks: ["Process improvement", "Root cause analysis", "Supplier quality management", "Complex judgement calls"], aiAdvantages: ["AI visual inspection systems", "Predictive quality analytics", "Automated reporting"], impactTimelineYears: [1, 4] },
  { title: "Production Manager", category: "Manufacturing", baseImpactScore: 35, automatableTasks: ["Production scheduling", "Inventory tracking", "KPI reporting", "Demand forecasting"], humanTasks: ["Team leadership", "Process optimisation strategy", "Supplier negotiations", "Crisis management"], aiAdvantages: ["AI production planning", "Predictive maintenance", "Demand forecasting tools"], impactTimelineYears: [3, 7] },
  { title: "Maintenance Technician", category: "Manufacturing", baseImpactScore: 30, automatableTasks: ["Scheduled maintenance tasks", "Diagnostic data analysis", "Parts ordering", "Documentation"], humanTasks: ["Complex troubleshooting", "Emergency repairs", "Equipment modification", "Safety assessment"], aiAdvantages: ["Predictive maintenance AI", "AR-guided repairs", "Automated diagnostics"], impactTimelineYears: [3, 7] },
  { title: "Supply Chain Manager", category: "Manufacturing", baseImpactScore: 45, automatableTasks: ["Order tracking", "Demand forecasting", "Inventory optimization", "Supplier performance reporting"], humanTasks: ["Supplier relationship management", "Risk mitigation strategy", "Negotiation", "Cross-functional coordination"], aiAdvantages: ["AI demand forecasting", "Automated logistics optimization", "Risk prediction tools"], impactTimelineYears: [2, 5] },
  { title: "Warehouse Worker", category: "Manufacturing", baseImpactScore: 78, automatableTasks: ["Picking and packing", "Inventory counting", "Sorting and shelving", "Loading and unloading"], humanTasks: ["Damage assessment", "Complex problem resolution", "Safety management", "Custom order handling"], aiAdvantages: ["Transition to robotics supervision", "Inventory management systems", "AI-guided picking"], impactTimelineYears: [1, 4] },
  // Retail
  { title: "Retail Sales Associate", category: "Retail", baseImpactScore: 68, automatableTasks: ["Checkout processing", "Stock checking", "Price enquiries", "Basic product recommendations"], humanTasks: ["Personal styling advice", "Complex customer service", "Visual merchandising", "Brand storytelling"], aiAdvantages: ["AI-powered clienteling", "Product knowledge augmentation", "Personalised recommendation tools"], impactTimelineYears: [1, 4] },
  { title: "Store Manager", category: "Retail", baseImpactScore: 35, automatableTasks: ["Inventory management", "Staff scheduling", "Sales reporting", "Reorder calculations"], humanTasks: ["Team leadership and coaching", "Customer experience strategy", "Community engagement", "Visual merchandising direction"], aiAdvantages: ["AI demand forecasting", "Staff optimization tools", "Customer analytics"], impactTimelineYears: [3, 7] },
  { title: "Visual Merchandiser", category: "Retail", baseImpactScore: 40, automatableTasks: ["Planogram generation", "Performance analytics", "Seasonal planning templates", "Competitor monitoring"], humanTasks: ["Creative display design", "Brand experience creation", "Sensory merchandising", "Local market adaptation"], aiAdvantages: ["AI layout optimisation", "Heat map analysis", "Trend prediction tools"], impactTimelineYears: [3, 6] },
  { title: "E-commerce Manager", category: "Retail", baseImpactScore: 45, automatableTasks: ["Product listing optimisation", "Pricing adjustments", "Inventory sync", "Review management"], humanTasks: ["Brand strategy", "Customer experience design", "Partnership development", "Market positioning"], aiAdvantages: ["AI pricing optimisation", "Personalisation engines", "Automated merchandising"], impactTimelineYears: [2, 5] },
  // Government
  { title: "Civil Servant", category: "Government", baseImpactScore: 45, automatableTasks: ["Form processing", "Data entry and verification", "Report generation", "Correspondence drafting"], humanTasks: ["Policy judgement", "Citizen engagement", "Complex case assessment", "Cross-agency coordination"], aiAdvantages: ["AI-powered citizen services", "Automated document processing", "Predictive resource allocation"], impactTimelineYears: [3, 7] },
  { title: "Policy Analyst", category: "Government", baseImpactScore: 35, automatableTasks: ["Data gathering and compilation", "Literature reviews", "Impact metric tracking", "Briefing document drafting"], humanTasks: ["Policy recommendation synthesis", "Stakeholder consultation", "Political context analysis", "Ethical framework application"], aiAdvantages: ["AI policy modelling", "Automated impact assessment", "Cross-jurisdictional analysis tools"], impactTimelineYears: [3, 8] },
  { title: "Urban Planner", category: "Government", baseImpactScore: 30, automatableTasks: ["Demographic data analysis", "Traffic flow modelling", "Zoning compliance checking", "Report generation"], humanTasks: ["Community engagement", "Vision and strategy", "Stakeholder negotiation", "Sustainability planning"], aiAdvantages: ["AI urban simulation", "Traffic prediction models", "Environmental impact tools"], impactTimelineYears: [4, 8] },
  { title: "Immigration Officer", category: "Government", baseImpactScore: 55, automatableTasks: ["Document verification", "Background check processing", "Application data entry", "Standard eligibility assessment"], humanTasks: ["Interview assessment", "Complex case judgement", "Fraud detection", "Humanitarian considerations"], aiAdvantages: ["AI document verification", "Risk scoring tools", "Automated processing systems"], impactTimelineYears: [2, 6] },
  // Agriculture
  { title: "Farm Manager", category: "Agriculture", baseImpactScore: 35, automatableTasks: ["Crop monitoring data collection", "Weather data analysis", "Inventory tracking", "Yield prediction"], humanTasks: ["Strategic crop planning", "Labour management", "Market relationships", "Land stewardship"], aiAdvantages: ["Precision agriculture AI", "Drone-based crop monitoring", "Predictive yield models"], impactTimelineYears: [3, 7] },
  { title: "Agricultural Scientist", category: "Agriculture", baseImpactScore: 30, automatableTasks: ["Data collection and analysis", "Literature review", "Standard experiment monitoring", "Report writing"], humanTasks: ["Research design", "Field observation and judgement", "Innovation and discovery", "Farmer engagement"], aiAdvantages: ["AI-powered research analysis", "Genomic analysis tools", "Automated experiment tracking"], impactTimelineYears: [4, 8] },
  { title: "Farm Worker", category: "Agriculture", baseImpactScore: 55, automatableTasks: ["Harvesting standard crops", "Sorting and grading", "Irrigation management", "Pest monitoring"], humanTasks: ["Specialty crop handling", "Equipment repair", "Animal welfare", "Local knowledge application"], aiAdvantages: ["Robotic harvesting assistance", "AI pest detection", "Precision irrigation tools"], impactTimelineYears: [3, 8] },
  // Media
  { title: "Journalist", category: "Media", baseImpactScore: 45, automatableTasks: ["Breaking news alerts", "Data-driven reporting", "Transcription", "Sports/financial results reporting"], humanTasks: ["Investigative journalism", "Source cultivation", "Narrative storytelling", "Ethical editorial judgement"], aiAdvantages: ["AI research assistants", "Automated transcription", "Data journalism tools"], impactTimelineYears: [2, 5] },
  { title: "Editor", category: "Media", baseImpactScore: 40, automatableTasks: ["Grammar and style checking", "Fact-checking assistance", "Headline generation", "Content scheduling"], humanTasks: ["Editorial judgement and taste", "Story development", "Writer mentoring", "Publication strategy"], aiAdvantages: ["AI editing assistants", "Automated fact-checking", "Content performance prediction"], impactTimelineYears: [2, 6] },
  { title: "Social Media Manager", category: "Media", baseImpactScore: 55, automatableTasks: ["Post scheduling", "Basic analytics reporting", "Hashtag research", "Content repurposing"], humanTasks: ["Community management", "Brand voice development", "Crisis communication", "Influencer relationships"], aiAdvantages: ["AI content generation", "Predictive engagement analytics", "Automated A/B testing"], impactTimelineYears: [1, 4] },
  { title: "Public Relations Specialist", category: "Media", baseImpactScore: 40, automatableTasks: ["Media monitoring", "Press release drafting", "Media list building", "Coverage reporting"], humanTasks: ["Media relationship building", "Crisis communication", "Strategic messaging", "Event management"], aiAdvantages: ["AI media monitoring", "Automated outreach tools", "Sentiment analysis"], impactTimelineYears: [2, 6] },
  { title: "Translator", category: "Media", baseImpactScore: 72, automatableTasks: ["Standard document translation", "Subtitle generation", "Glossary management", "Terminology consistency"], humanTasks: ["Literary and creative translation", "Cultural nuance adaptation", "Legal/medical precision", "Interpreting"], aiAdvantages: ["AI translation tools", "Real-time translation assistance", "Translation memory integration"], impactTimelineYears: [1, 3] },
  // Additional common roles
  { title: "Customer Service Representative", category: "Retail", baseImpactScore: 75, automatableTasks: ["FAQ responses", "Order status enquiries", "Password resets", "Basic complaint handling"], humanTasks: ["Complex complaint resolution", "Emotional support", "Upselling through relationship", "Edge case handling"], aiAdvantages: ["AI chatbot management", "Sentiment-guided responses", "Escalation prediction"], impactTimelineYears: [1, 3] },
  { title: "Human Resources Manager", category: "Government", baseImpactScore: 40, automatableTasks: ["Resume screening", "Payroll processing", "Benefits administration", "Compliance reporting"], humanTasks: ["Employee relations", "Culture development", "Strategic workforce planning", "Conflict resolution"], aiAdvantages: ["AI recruitment tools", "Employee sentiment analysis", "Workforce analytics"], impactTimelineYears: [2, 6] },
  { title: "Marketing Manager", category: "Media", baseImpactScore: 40, automatableTasks: ["Campaign analytics", "A/B test execution", "Content calendar management", "Ad copy variations"], humanTasks: ["Brand strategy", "Creative direction", "Market positioning", "Customer insight synthesis"], aiAdvantages: ["AI-powered targeting", "Automated campaign optimisation", "Predictive analytics"], impactTimelineYears: [2, 5] },
  { title: "Project Manager", category: "Technology", baseImpactScore: 35, automatableTasks: ["Status report generation", "Schedule tracking", "Resource allocation", "Risk register updates"], humanTasks: ["Stakeholder management", "Team motivation", "Conflict resolution", "Strategic decision-making"], aiAdvantages: ["AI project forecasting", "Automated status tracking", "Risk prediction tools"], impactTimelineYears: [3, 7] },
  { title: "Executive Assistant", category: "Government", baseImpactScore: 60, automatableTasks: ["Calendar management", "Email sorting", "Meeting notes", "Travel booking"], humanTasks: ["Relationship management", "Anticipating executive needs", "Confidential communication", "Event coordination"], aiAdvantages: ["AI scheduling assistants", "Automated email management", "Meeting summarisation"], impactTimelineYears: [1, 4] },
  { title: "Real Estate Agent", category: "Finance", baseImpactScore: 45, automatableTasks: ["Property listing descriptions", "Market analysis reports", "Lead scoring", "Virtual tour creation"], humanTasks: ["Client relationship building", "Negotiation", "Local market expertise", "Property viewings and staging"], aiAdvantages: ["AI property valuation", "Automated matching", "Virtual staging tools"], impactTimelineYears: [2, 6] },
  { title: "Chef", category: "Retail", baseImpactScore: 15, automatableTasks: ["Inventory ordering", "Menu costing", "Recipe scaling", "Nutritional calculations"], humanTasks: ["Creative menu development", "Taste and flavour expertise", "Kitchen leadership", "Customer experience"], aiAdvantages: ["AI menu optimisation", "Inventory prediction", "Trend analysis tools"], impactTimelineYears: [5, 10] },
  { title: "Driver", category: "Manufacturing", baseImpactScore: 65, automatableTasks: ["Route planning", "Fuel optimisation", "Delivery scheduling", "Vehicle diagnostics"], humanTasks: ["Complex navigation decisions", "Customer interaction", "Safety judgement", "Loading and securing cargo"], aiAdvantages: ["AI route optimisation", "Fleet management tools", "Safety monitoring systems"], impactTimelineYears: [3, 8] },
  { title: "Construction Worker", category: "Manufacturing", baseImpactScore: 25, automatableTasks: ["Material quantity calculations", "Progress tracking", "Safety checklist automation", "Equipment scheduling"], humanTasks: ["Skilled craftsmanship", "Site safety judgement", "Problem-solving on site", "Team coordination"], aiAdvantages: ["AI site monitoring", "BIM integration", "Safety prediction tools"], impactTimelineYears: [5, 10] },
  { title: "Electrician", category: "Manufacturing", baseImpactScore: 20, automatableTasks: ["Wiring diagrams", "Load calculations", "Code compliance checking", "Parts ordering"], humanTasks: ["Hands-on installation", "Troubleshooting", "Safety assessment", "Custom solutions"], aiAdvantages: ["AR-guided wiring", "AI fault diagnosis", "Smart building integration"], impactTimelineYears: [5, 10] },
  { title: "Plumber", category: "Manufacturing", baseImpactScore: 18, automatableTasks: ["Parts identification", "Quote generation", "Scheduling", "Code reference"], humanTasks: ["Hands-on repair work", "Diagnostic assessment", "Emergency response", "Customer communication"], aiAdvantages: ["AI diagnostic tools", "AR repair guidance", "Smart leak detection"], impactTimelineYears: [5, 10] },
  { title: "Receptionist", category: "Retail", baseImpactScore: 72, automatableTasks: ["Call routing", "Appointment scheduling", "Visitor check-in", "Information enquiries"], humanTasks: ["VIP guest management", "Complex enquiry handling", "Office atmosphere maintenance", "Emergency coordination"], aiAdvantages: ["AI virtual receptionists", "Automated scheduling", "Visitor management systems"], impactTimelineYears: [1, 3] },
  { title: "Security Guard", category: "Government", baseImpactScore: 50, automatableTasks: ["CCTV monitoring", "Access control", "Patrol scheduling", "Incident reporting"], humanTasks: ["Physical intervention", "Judgement in emergencies", "De-escalation", "Customer service"], aiAdvantages: ["AI surveillance analysis", "Anomaly detection", "Access management systems"], impactTimelineYears: [2, 6] },
  { title: "Research Scientist", category: "Education", baseImpactScore: 25, automatableTasks: ["Literature review", "Data analysis", "Lab experiment monitoring", "Grant application formatting"], humanTasks: ["Hypothesis generation", "Experimental design", "Peer collaboration", "Scientific creativity"], aiAdvantages: ["AI research discovery", "Automated data analysis", "Literature synthesis tools"], impactTimelineYears: [4, 9] },
  { title: "Veterinarian", category: "Healthcare", baseImpactScore: 15, automatableTasks: ["Medical records", "Appointment scheduling", "Drug dosage calculations", "Lab result interpretation assistance"], humanTasks: ["Animal examination", "Surgical procedures", "Owner communication", "Diagnostic judgement"], aiAdvantages: ["AI diagnostic support", "Telemedicine tools", "Practice management automation"], impactTimelineYears: [5, 10] },
  { title: "Flight Attendant", category: "Retail", baseImpactScore: 20, automatableTasks: ["Safety briefing delivery", "Meal ordering systems", "Schedule management", "Passenger manifests"], humanTasks: ["Passenger safety management", "Emergency response", "Customer care and comfort", "Conflict resolution"], aiAdvantages: ["AI-powered passenger profiles", "Service personalisation", "Predictive scheduling"], impactTimelineYears: [5, 10] },
  { title: "Pilot", category: "Manufacturing", baseImpactScore: 30, automatableTasks: ["Route calculations", "Pre-flight checklists", "Weather analysis", "Fuel planning"], humanTasks: ["Emergency decision-making", "Crew management", "Passenger safety", "Complex landing situations"], aiAdvantages: ["Enhanced autopilot systems", "AI weather prediction", "Predictive maintenance alerts"], impactTimelineYears: [5, 12] },

  // =====================
  // NEW CATEGORIES BELOW
  // =====================

  // Sales
  { title: "Account Executive", category: "Sales", baseImpactScore: 45, automatableTasks: ["CRM data entry and updating", "Follow-up email drafting", "Pipeline reporting", "Meeting scheduling"], humanTasks: ["Relationship building and trust", "Complex deal negotiation", "Strategic account planning", "Understanding client pain points"], aiAdvantages: ["AI-powered lead scoring", "Automated outreach sequences", "Deal intelligence and coaching"], impactTimelineYears: [2, 6] },
  { title: "Sales Director", category: "Sales", baseImpactScore: 35, automatableTasks: ["Sales forecasting", "Performance dashboard generation", "Territory planning analytics", "Competitive intelligence gathering"], humanTasks: ["Team leadership and motivation", "Enterprise relationship management", "Sales strategy design", "Board-level communication"], aiAdvantages: ["AI revenue forecasting", "Coaching analytics", "Market trend prediction"], impactTimelineYears: [3, 7] },
  { title: "Business Development Representative", category: "Sales", baseImpactScore: 55, automatableTasks: ["Cold outreach personalisation", "Lead qualification scoring", "Meeting booking", "Research on prospects"], humanTasks: ["Creative outreach strategy", "Building rapport from scratch", "Understanding nuanced needs", "Adapting pitch in real-time"], aiAdvantages: ["AI-generated outreach sequences", "Automated lead enrichment", "Intent signal detection"], impactTimelineYears: [1, 4] },
  { title: "Sales Engineer", category: "Sales", baseImpactScore: 30, automatableTasks: ["Demo environment setup", "Technical documentation", "RFP response drafting", "Feature comparison matrices"], humanTasks: ["Custom solution architecture", "Live technical demos", "Trust building with technical buyers", "Translating business needs to tech"], aiAdvantages: ["AI-assisted demo generation", "Automated RFP responses", "Knowledge base synthesis"], impactTimelineYears: [3, 7] },
  { title: "Insurance Sales Agent", category: "Sales", baseImpactScore: 60, automatableTasks: ["Quote generation", "Policy comparison", "Renewal reminders", "Claims status updates"], humanTasks: ["Needs assessment and empathy", "Complex policy explanation", "Life event advisory", "Trust and relationship building"], aiAdvantages: ["AI policy recommendation engines", "Automated quoting systems", "Predictive customer needs"], impactTimelineYears: [2, 5] },
  { title: "Pharmaceutical Sales Rep", category: "Sales", baseImpactScore: 50, automatableTasks: ["Product information compilation", "Call planning and routing", "Sample tracking", "Compliance documentation"], humanTasks: ["Physician relationship building", "Clinical discussion facilitation", "Territory strategy", "Navigating hospital systems"], aiAdvantages: ["AI-driven physician targeting", "Automated compliance tracking", "Personalised engagement insights"], impactTimelineYears: [2, 6] },
  { title: "Car Sales Representative", category: "Sales", baseImpactScore: 55, automatableTasks: ["Inventory matching", "Finance calculation", "Follow-up scheduling", "Trade-in valuations"], humanTasks: ["Test drive experience", "Negotiation and closing", "Emotional buying guidance", "After-sales relationship"], aiAdvantages: ["AI customer preference matching", "Automated lead nurturing", "Virtual showroom tools"], impactTimelineYears: [2, 5] },

  // Consulting & Professional Services
  { title: "Management Consultant", category: "Consulting", baseImpactScore: 40, automatableTasks: ["Market research compilation", "Slide deck data population", "Benchmarking analysis", "Financial modelling"], humanTasks: ["Client relationship management", "Problem framing and structuring", "Stakeholder facilitation", "Change management leadership"], aiAdvantages: ["AI-powered research synthesis", "Automated slide generation", "Data-driven recommendations"], impactTimelineYears: [3, 7] },
  { title: "Strategy Consultant", category: "Consulting", baseImpactScore: 35, automatableTasks: ["Competitive landscape mapping", "Data analysis and visualisation", "Industry report synthesis", "Scenario modelling"], humanTasks: ["Strategic insight and vision", "C-suite advisory", "Workshop facilitation", "Cross-industry pattern recognition"], aiAdvantages: ["AI strategy simulation", "Market intelligence automation", "Trend prediction models"], impactTimelineYears: [3, 8] },
  { title: "IT Consultant", category: "Consulting", baseImpactScore: 45, automatableTasks: ["System assessment reports", "Vendor comparison matrices", "Architecture documentation", "Migration planning templates"], humanTasks: ["Technology strategy advisory", "Change management", "Stakeholder alignment", "Custom solution design"], aiAdvantages: ["AI-powered system analysis", "Automated architecture recommendations", "Cost-benefit modelling"], impactTimelineYears: [2, 6] },
  { title: "Tax Consultant", category: "Consulting", baseImpactScore: 55, automatableTasks: ["Tax calculation and filing", "Deduction identification", "Compliance checking", "Document organisation"], humanTasks: ["Cross-border tax strategy", "Client advisory on complex structures", "Regulatory interpretation", "Audit representation"], aiAdvantages: ["AI tax optimisation engines", "Automated filing systems", "Regulatory change monitoring"], impactTimelineYears: [2, 5] },
  { title: "Recruitment Consultant", category: "Consulting", baseImpactScore: 60, automatableTasks: ["Resume screening and shortlisting", "Job description writing", "Interview scheduling", "Candidate sourcing"], humanTasks: ["Candidate relationship building", "Cultural fit assessment", "Salary negotiation", "Client needs interpretation"], aiAdvantages: ["AI candidate matching", "Automated outreach campaigns", "Predictive hiring analytics"], impactTimelineYears: [1, 4] },
  { title: "Business Analyst", category: "Consulting", baseImpactScore: 50, automatableTasks: ["Requirements documentation", "Process flow mapping", "Data analysis reports", "User story writing"], humanTasks: ["Stakeholder interview and elicitation", "Complex problem decomposition", "Change impact assessment", "Cross-team facilitation"], aiAdvantages: ["AI requirements analysis", "Automated documentation", "Process mining tools"], impactTimelineYears: [2, 5] },

  // Operations & Logistics
  { title: "Operations Manager", category: "Operations", baseImpactScore: 40, automatableTasks: ["KPI dashboard generation", "Process monitoring", "Resource scheduling", "Vendor performance tracking"], humanTasks: ["Process improvement strategy", "Team leadership and coaching", "Crisis management", "Cross-functional coordination"], aiAdvantages: ["AI process optimisation", "Predictive resource planning", "Automated bottleneck detection"], impactTimelineYears: [2, 6] },
  { title: "Logistics Coordinator", category: "Operations", baseImpactScore: 55, automatableTasks: ["Shipment tracking", "Route optimisation", "Documentation processing", "Carrier rate comparison"], humanTasks: ["Exception handling and problem-solving", "Carrier relationship management", "Custom logistics solutions", "Regulatory compliance navigation"], aiAdvantages: ["AI route optimisation", "Automated shipment tracking", "Demand-driven logistics planning"], impactTimelineYears: [2, 5] },
  { title: "Procurement Manager", category: "Operations", baseImpactScore: 45, automatableTasks: ["Purchase order processing", "Supplier comparison", "Spend analysis", "Contract renewal tracking"], humanTasks: ["Supplier negotiation", "Strategic sourcing decisions", "Risk assessment", "Relationship management"], aiAdvantages: ["AI spend analytics", "Automated supplier evaluation", "Predictive procurement"], impactTimelineYears: [2, 6] },
  { title: "Inventory Manager", category: "Operations", baseImpactScore: 60, automatableTasks: ["Stock level monitoring", "Reorder point calculations", "Demand forecasting", "Shrinkage tracking"], humanTasks: ["Inventory strategy and planning", "Supplier coordination", "Seasonal adjustments", "Loss prevention strategy"], aiAdvantages: ["AI demand prediction", "Automated replenishment", "Real-time inventory optimisation"], impactTimelineYears: [1, 4] },
  { title: "Shipping Coordinator", category: "Operations", baseImpactScore: 55, automatableTasks: ["Shipping label generation", "Customs documentation", "Carrier selection", "Delivery status updates"], humanTasks: ["Exception and delay management", "International compliance", "Customer escalation handling", "Process improvement"], aiAdvantages: ["AI carrier selection", "Automated customs processing", "Predictive delivery estimation"], impactTimelineYears: [2, 5] },

  // Asia-Specific / Emerging
  { title: "E-sports Professional", category: "Asia-Specific", baseImpactScore: 15, automatableTasks: ["Match replay analysis", "Performance stat tracking", "Social media scheduling", "Training drill generation"], humanTasks: ["In-game decision-making and reflexes", "Team communication and synergy", "Mental resilience and composure", "Fan engagement and personality"], aiAdvantages: ["AI opponent analysis", "Performance coaching analytics", "Content creation automation"], impactTimelineYears: [5, 10] },
  { title: "K-pop / Entertainment Manager", category: "Asia-Specific", baseImpactScore: 25, automatableTasks: ["Social media analytics", "Schedule coordination", "Fan engagement metrics", "Content calendar planning"], humanTasks: ["Talent development and mentoring", "Creative direction", "Industry relationship building", "Crisis and reputation management"], aiAdvantages: ["AI trend prediction", "Automated fan sentiment analysis", "Content optimisation tools"], impactTimelineYears: [4, 8] },
  { title: "Semiconductor Engineer", category: "Asia-Specific", baseImpactScore: 20, automatableTasks: ["Design rule checking", "Simulation setup", "Test pattern generation", "Documentation"], humanTasks: ["Novel chip architecture design", "Process optimisation innovation", "Failure analysis and debugging", "Cross-team integration"], aiAdvantages: ["AI-assisted chip design", "Automated testing and verification", "Yield prediction models"], impactTimelineYears: [4, 9] },
  { title: "Manufacturing Engineer", category: "Asia-Specific", baseImpactScore: 35, automatableTasks: ["Process documentation", "Quality data analysis", "Equipment monitoring", "Standard operating procedures"], humanTasks: ["Process innovation and optimisation", "Equipment selection and integration", "Safety system design", "Cross-functional problem solving"], aiAdvantages: ["AI process optimisation", "Predictive quality control", "Digital twin simulation"], impactTimelineYears: [3, 7] },
  { title: "Tea / Coffee Buyer", category: "Asia-Specific", baseImpactScore: 30, automatableTasks: ["Market price tracking", "Supply chain logistics", "Quality grading documentation", "Inventory management"], humanTasks: ["Sensory evaluation and cupping", "Origin relationship building", "Quality assessment expertise", "Trend and flavour forecasting"], aiAdvantages: ["AI market price prediction", "Supply chain optimisation", "Quality grading assistance"], impactTimelineYears: [4, 8] },
  { title: "Tourism Guide", category: "Asia-Specific", baseImpactScore: 40, automatableTasks: ["Itinerary planning", "Historical fact compilation", "Booking coordination", "Language translation"], humanTasks: ["Storytelling and cultural interpretation", "Group dynamics management", "Emergency handling", "Authentic local experiences"], aiAdvantages: ["AI-powered multilingual support", "Personalised itinerary generation", "Real-time translation tools"], impactTimelineYears: [3, 7] },
  { title: "Export Trade Specialist", category: "Asia-Specific", baseImpactScore: 45, automatableTasks: ["Customs documentation", "Tariff classification", "Compliance checking", "Shipping logistics coordination"], humanTasks: ["Trade negotiation", "Market entry strategy", "Regulatory navigation", "Cross-cultural relationship building"], aiAdvantages: ["AI trade compliance tools", "Automated documentation", "Market intelligence analysis"], impactTimelineYears: [2, 6] },
  { title: "Fintech Product Manager", category: "Asia-Specific", baseImpactScore: 35, automatableTasks: ["Market research aggregation", "User analytics reporting", "Competitive feature analysis", "Sprint documentation"], humanTasks: ["Product vision and strategy", "Regulatory compliance navigation", "User empathy and research", "Stakeholder management"], aiAdvantages: ["AI user behaviour analysis", "Automated A/B testing", "Regulatory change monitoring"], impactTimelineYears: [3, 7] },

  // Additional Common Roles
  { title: "CEO / Managing Director", category: "Leadership", baseImpactScore: 20, automatableTasks: ["Report compilation", "Meeting preparation briefs", "Market intelligence gathering", "Email triage"], humanTasks: ["Strategic vision and leadership", "Stakeholder and board management", "Culture building", "Crisis decision-making"], aiAdvantages: ["AI executive briefings", "Market intelligence synthesis", "Scenario planning tools"], impactTimelineYears: [5, 10] },
  { title: "CFO / Finance Director", category: "Leadership", baseImpactScore: 30, automatableTasks: ["Financial reporting", "Budget variance analysis", "Cash flow forecasting", "Compliance document preparation"], humanTasks: ["Financial strategy and capital allocation", "Investor relations", "Risk management leadership", "Board advisory"], aiAdvantages: ["AI financial forecasting", "Real-time reporting dashboards", "Risk modelling tools"], impactTimelineYears: [3, 7] },
  { title: "CTO / Chief Technology Officer", category: "Leadership", baseImpactScore: 25, automatableTasks: ["Technology landscape scanning", "Vendor evaluation reports", "Architecture documentation", "Performance benchmarking"], humanTasks: ["Technology vision and strategy", "Team building and culture", "Innovation leadership", "Executive communication"], aiAdvantages: ["AI technology assessment", "Automated code quality monitoring", "Innovation trend tracking"], impactTimelineYears: [4, 8] },
  { title: "Startup Founder", category: "Leadership", baseImpactScore: 20, automatableTasks: ["Market research compilation", "Pitch deck data population", "Financial model templates", "Competitor monitoring"], humanTasks: ["Vision and storytelling", "Fundraising and investor relations", "Team building", "Product-market fit intuition"], aiAdvantages: ["AI market analysis", "Automated pitch preparation", "Customer discovery acceleration"], impactTimelineYears: [4, 9] },
  { title: "Freelance Writer", category: "Creative", baseImpactScore: 65, automatableTasks: ["SEO content generation", "First draft creation", "Research compilation", "Content repurposing"], humanTasks: ["Unique voice and perspective", "Deep investigative research", "Client relationship management", "Niche expertise and thought leadership"], aiAdvantages: ["AI writing assistants for speed", "Automated research tools", "SEO optimisation suggestions"], impactTimelineYears: [1, 3] },
  { title: "Personal Trainer", category: "Healthcare", baseImpactScore: 15, automatableTasks: ["Workout plan generation", "Progress tracking", "Nutritional calculations", "Session scheduling"], humanTasks: ["Motivation and accountability", "Form correction and safety", "Personalised coaching", "Emotional support and goal setting"], aiAdvantages: ["AI workout programming", "Wearable data integration", "Progress analytics"], impactTimelineYears: [5, 10] },
  { title: "Physiotherapist", category: "Healthcare", baseImpactScore: 20, automatableTasks: ["Exercise prescription templates", "Progress documentation", "Appointment scheduling", "Outcome measurement tracking"], humanTasks: ["Hands-on manual therapy", "Clinical assessment and diagnosis", "Patient motivation", "Treatment adaptation"], aiAdvantages: ["AI movement analysis", "Personalised rehab programs", "Remote monitoring platforms"], impactTimelineYears: [5, 10] },
  { title: "Social Worker", category: "Healthcare", baseImpactScore: 20, automatableTasks: ["Case documentation", "Resource directory searches", "Report generation", "Appointment scheduling"], humanTasks: ["Client advocacy and empathy", "Crisis intervention", "Complex case assessment", "Community relationship building"], aiAdvantages: ["AI case management tools", "Resource matching systems", "Risk assessment analytics"], impactTimelineYears: [5, 10] },
  { title: "Psychologist", category: "Healthcare", baseImpactScore: 20, automatableTasks: ["Assessment scoring", "Session note templates", "Research literature reviews", "Scheduling management"], humanTasks: ["Therapeutic relationship building", "Clinical assessment and diagnosis", "Treatment planning", "Ethical decision-making"], aiAdvantages: ["AI-assisted diagnostics", "Outcome tracking tools", "Research synthesis aids"], impactTimelineYears: [5, 10] },
  { title: "Interior Designer", category: "Creative", baseImpactScore: 35, automatableTasks: ["Mood board generation", "3D room rendering", "Material sourcing", "Budget estimation"], humanTasks: ["Client vision interpretation", "Spatial creativity", "Project management", "Vendor and contractor coordination"], aiAdvantages: ["AI room visualisation", "Generative design options", "Automated material matching"], impactTimelineYears: [3, 7] },
  { title: "Event Planner", category: "Creative", baseImpactScore: 40, automatableTasks: ["Venue comparison", "Budget tracking", "Guest list management", "Vendor coordination scheduling"], humanTasks: ["Creative event concept design", "Crisis management on-site", "Client relationship building", "Real-time problem solving"], aiAdvantages: ["AI venue matching", "Automated logistics planning", "Budget optimisation tools"], impactTimelineYears: [3, 7] },
  { title: "Fitness Instructor", category: "Healthcare", baseImpactScore: 15, automatableTasks: ["Class playlist curation", "Attendance tracking", "Workout routine generation", "Social media posting"], humanTasks: ["Live class energy and motivation", "Form correction and safety", "Community building", "Adapting to group dynamics"], aiAdvantages: ["AI workout design", "Music tempo matching", "Participant engagement analytics"], impactTimelineYears: [5, 10] },
  { title: "Barista", category: "Retail", baseImpactScore: 25, automatableTasks: ["Inventory tracking", "Order queue management", "Recipe consistency", "Sales reporting"], humanTasks: ["Customer rapport and service", "Latte art and craft", "Menu creativity", "Atmosphere curation"], aiAdvantages: ["AI inventory prediction", "Automated ordering systems", "Customer preference tracking"], impactTimelineYears: [4, 8] },
  { title: "Hairdresser / Stylist", category: "Retail", baseImpactScore: 15, automatableTasks: ["Appointment scheduling", "Inventory management", "Style reference gathering", "Social media posting"], humanTasks: ["Hands-on cutting and styling", "Client consultation and vision", "Colour theory expertise", "Building repeat clientele"], aiAdvantages: ["AI style recommendation", "Virtual try-on tools", "Client preference tracking"], impactTimelineYears: [5, 10] },
];

/**
 * Simple fuzzy matching: find the best role match for a given query.
 */
export function findBestRoleMatch(query: string): RoleData | null {
  const q = query.toLowerCase().trim();
  if (!q) return null;

  // Exact match
  const exact = ROLES.find((r) => r.title.toLowerCase() === q);
  if (exact) return exact;

  // Starts with match
  const startsWith = ROLES.find((r) => r.title.toLowerCase().startsWith(q));
  if (startsWith) return startsWith;

  // Contains match
  const contains = ROLES.find((r) => r.title.toLowerCase().includes(q));
  if (contains) return contains;

  // Word overlap scoring
  const queryWords = q.split(/\s+/);
  let bestScore = 0;
  let bestMatch: RoleData | null = null;

  for (const role of ROLES) {
    const titleWords = role.title.toLowerCase().split(/\s+/);
    let score = 0;
    for (const qw of queryWords) {
      for (const tw of titleWords) {
        if (tw.includes(qw) || qw.includes(tw)) {
          score += 1;
        }
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = role;
    }
  }

  return bestScore > 0 ? bestMatch : null;
}

export function calculateScore(role: RoleData, country: CountryData): number {
  return Math.min(100, Math.max(0, Math.round(role.baseImpactScore * country.adoptionMultiplier)));
}

export function getScoreLabel(score: number): { label: string; color: string } {
  if (score <= 25) return { label: "AI-Resistant", color: "hsl(142, 71%, 45%)" };
  if (score <= 50) return { label: "Evolving", color: "hsl(48, 96%, 53%)" };
  if (score <= 75) return { label: "Transforming", color: "hsl(25, 95%, 53%)" };
  return { label: "Disrupting", color: "hsl(0, 84%, 60%)" };
}

export function getScoreGradient(score: number): string {
  if (score <= 25) return "from-green-500 to-green-400";
  if (score <= 50) return "from-yellow-500 to-amber-400";
  if (score <= 75) return "from-orange-500 to-orange-400";
  return "from-red-500 to-red-400";
}

/** Get category stats for the comparison section */
export function getCategoryStats(category: string): { avg: number; minRole: RoleData; maxRole: RoleData } {
  const rolesInCategory = ROLES.filter((r) => r.category === category);
  if (rolesInCategory.length === 0) {
    return { avg: 45, minRole: ROLES[0], maxRole: ROLES[0] };
  }
  const avg = Math.round(rolesInCategory.reduce((sum, r) => sum + r.baseImpactScore, 0) / rolesInCategory.length);
  const sorted = [...rolesInCategory].sort((a, b) => a.baseImpactScore - b.baseImpactScore);
  return { avg, minRole: sorted[0], maxRole: sorted[sorted.length - 1] };
}
